apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
    - name: app
      command: ["/bin/sh", "-c", "printenv; sleep 3600"]
      image: busybox:latest
      envFrom:
        - configMapRef:
            name: myconfigmap

# this pod will get all the environment variables from the configmap

# kubectl logs env-configmap
# kubectl exec -it env-configmap -- printenv | grep name
# this will print the env variable name from the configmap