apiVersion: v1 
kind: Pod
metadata:
  name: mem-demo2
  namespace: mem-example
spec:
  containers:
   - name: mem-demo2
     image: polinux/stress # image for stress testing
     resources:
       limits:
         memory: "200Mi"
       requests:
         memory: "100Mi"
     command: ["stress"]
     args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

     # this pod will not be scheduled because OOM will kill the pod
     # as the limit is set to 200Mi and the stress command will use 250M