apiVersion: v1 
kind: Pod
metadata:
  name: mem-demo3
  namespace: mem-example
spec:
  containers:
   - name: mem-demo3
     image: polinux/stress # image for stress testing
     resources:
       limits:
         memory: "1000Gi"
       requests:
         memory: "1000Gi"
     command: ["stress"]
     args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]