apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd


  # preferredDuringSchedulingIgnoredDuringExecution: will prefer to schedule the pod on a node that has the label disktype=hdd.
  # If no node with that label is available, a node without the label will be used.