apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-planea
  extraPortMappings:          # this is needed for nodeport or loadbalancer services
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
- role: worker
- role: worker
- role: worker
