apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP




    #  DaemonSet is a Kubernetes resource that ensures that all (or some) nodes
    #  run a copy of a Pod. As nodes are added to the cluster, Pods are added 
    #  to them. As nodes are removed from the cluster, those Pods are garbage 
    #  collected. Deleting a DaemonSet will clean up the Pods it created.